version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfiles.dev
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_DB=django-stripe
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - PUBLISH_KEY=
      - API_KEY_STRIPE=
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: django-stripe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: